### ISSUE TITLE
Make Map.Viewport setable

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#132]
I want to change Map.Viewport from Viewport to NotifyingViewport. So it is possible get events when the Center or the Resolution of the Viewport changing.

If this is possible, than I could provide a PR.

**Comment by pauldendulk** [comment]
At some point I used the NotifyingViewport as the default but removed it because of performance. I am not sure at this point if I should make it settable or just create a single Viewport that notifies. Also I am not so sure if all the separate properties are helpful. In most cases I think you just want to know if the viewport has changed so a single ViewportChanged event might suffice.

**Comment by charlenni** [comment]
That's correct, but in the moment, there is no event for changing the center. With the workaround, to take the normal Viewport and replace it with a NotifyingViewport as wrapper, I get it. Works now.

**Comment by pauldendulk** [comment]
After some thought I decided to go for the ViewportChanged event on the Viewport. I think in most scenarios you just want to know the change and not which specific property. Having to check all the separate properties is error prone. Also one change could fire multiple property changed events. Could you check if this is sufficient for what you are trying to do?
