### ISSUE TITLE
Marker from Resource

### ISSUE THREAD

**Issue by johnhs91** [pauldendulk/Mapsui#135]
Hi

What's the best way to add a simple marker from Resource drawable.

We've used OsmSharp to our app untill now, but got major issues with memory, so we'r gonna try out MapSui, to see if it's better. 
But as i see there isn't a easy way to add markers as in OsmSharp. I need to create layer for each marker ?(Same as OsmSharp, but they got a Marker class, that makes it easier)
And if I change tile afterwards (We got ALOT of tiles, to choose between) do I need to redraw all markers, to get them on top of view?

Br. John Sørensen

**Comment by pauldendulk** [comment]
In Mapsui you use points with a symbol style. The symbol style can be a bitmap. The style can be on the layer or on a specific feature.  There is a sample here: https://github.com/pauldendulk/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/VariousSample.cs

The symbols are rendered by the Mapsui renderer (skia of wpf on desktop) and not by the platform (like ios, android).

**Comment by pauldendulk** [comment]
btw, with respect to resources. The bitmap should be registered once and then be referenced from the symbols with bitmapId. So

**Comment by pauldendulk** [comment]
When you select another layer the map should redraw itself automatically.

**Comment by johnhs91** [comment]
Thank you very much.
I can now show markers. The problem is, the image need to be on top of the coordinate, and not middle.
So if I zoom, the bottom of marker follow the coordinate.
Any easy way to do that? 

Br. John Sørensen

**Comment by pauldendulk** [comment]
Use offset.

Paul

Op 28 feb. 2017 13:44 schreef "johnhs91" <notifications@github.com>:

Thank you very much.
I can now show markers. The problem is, the image need to be on top of the
coordinate, and not middle.
So if I zoom, the bottom of marker follow the coordinate.
Any easy way to do that?

Br. John Sørensen

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pauldendulk/Mapsui/issues/135#issuecomment-283029468>,
or mute the thread
