### ISSUE TITLE
Skia BitmapHelpers.RenderRaster: Bitmap drawn twice?

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#143]
Is it correct, that the Bitmap is drawn twice in Mapsui.Rendering.Skia-PCL/BitmapHelper.cs, line 58? Perhaps one time is enough?

**Comment by pauldendulk** [comment]
oh wow!! I should be really ashamed but I am happy instead :). Simply removing the first one is a big performance improvement. More than twice because the first one is much slower. Perhaps eventually this should be an option. Per layer I would think.

This occurred when I was comparing the performance of the two methods and accidentally committed them both.

**Comment by charlenni** [comment]
Good to hear. Making things faster is always a good news.

Found it while debuging, because my Xamarin.Forms implementation didn't draw any tiles after the last updates :(. Perhaps you have a suggestion? The tiles are fetched. I could see the data comming in. But they are never drawn. CanvasOnPaintSurface of SKCanvasView is called only once when starting app and than never again. I could change the viewport with tap or with code, no reaction. Perhaps something change in behavior with PR "sk canvas now a member of MapControl instead of MapControl derived from". Your Android example works ok, but Xamarin.Forms fail :(. Any idee where to search?

**Comment by pauldendulk** [comment]
Fixed with https://github.com/pauldendulk/Mapsui/commit/542a017f5926927bb3fe4a5c771e3aab542d23e6
