### ISSUE TITLE
Disposed issues

### ISSUE THREAD

**Issue by johnhs91** [pauldendulk/Mapsui#147]
Hi 

I have issues with MapControl beeing disposed all the time.
I get this error every single time it happens.
Looks like it's resource designer every time.
Don't know if it's because I use Xamarin.forms.

Actualy though it was because of navigation it disposed the object, but this time, my app was running for 1-2 minutes, and then I started dragging again, and it happend.

![image](https://cloud.githubusercontent.com/assets/4305618/23790184/5f04f3dc-057e-11e7-844e-bc4fb16db03f.png)

**Comment by pauldendulk** [comment]
If it is the entire MapControl than it is probably not caused by Mapsui itself. 

Can you say anything about when this happen? How often? What are you doing when it happens?

What might be related is that in Android when you change orientation the entire view is build from scratch.

You are now working with the Xamarin.Forms wrapper solution. I was thinking about building a ' native' Xamarin.Forms MapControl. Perhaps this will be less problematic. I

I know little about Xamarin.Forms at the moment. Does it support multitouch? How does it go about orientation change?

**Comment by johnhs91** [comment]
Well most of the time it's because I'm navigating. But this time I didn't do anything at all, just waited 2 minutes, and zoomed again.
Only android code I got is the initialize, where I set the native view, it's all.

Can't find a system in the crash sadly.

**Comment by johnhs91** [comment]
I'll check if there are better stack trace. I'll come back with more info later.

**Comment by johnhs91** [comment]
I got a event that run if unit find new GPS, is it possible that, if it find GPS (It update marker lat and lon) there is an event in Mapsui that try to update something disposed?
But don't know why this should happen since it's resource designer.

**Comment by johnhs91** [comment]
I can get this every single time I make a fast navigate, to a page with map and away again. Then it crash every time.

**Comment by pauldendulk** [comment]
Could it be the page with the MapControl is completely disposed and rebuild when you navigate back?

**Comment by pauldendulk** [comment]
Btw. Do you use separate layers for each marker? This is not how Mapsui was intended. Performance might be better if the markers are in one layer.

**Comment by johnhs91** [comment]
I could make same layer for marker's problem is some markers change color at some point, and can't do that.
So need to make seperate layers.

And yes it does dispose MapControl when navigating away. Since it's a page, it doesn't keep reference.

**Comment by johnhs91** [comment]
But if I navigate to a page with mapview and away, it shouldn't crash, just stop initializing, or just dispose.

**Comment by pauldendulk** [comment]
If you navigate away and the location change event is triggered the MapControl could be null. Also you at some point a new MapControl could be receated while you are working with the old one. Just guessing here but I assume something like that is happening.

**Comment by pauldendulk** [comment]
In Mapsui each symbol can have it's own style. You can set a style on the feature instead of the map (you could also use both at the same time).

There is also a thematic style. Where the style depends on the state of the feature. For some scenarios this is the easiest. You have some logic to decide your symbol style right? So it is possible to put that logic in the thematic style.

**Comment by johnhs91** [comment]
Nice about feature's, does it have name too? or do I need to add that myself then?
Using that to see what marker is clicked.

**Comment by pauldendulk** [comment]
You create a method that get the Feature as argument. You can return a style base on that Feature. You have to add the 'name' as a key-value to the feature.

https://github.com/pauldendulk/Mapsui/blob/master/Mapsui/Styles/Thematics/ThemeStyle.cs

**Comment by johnhs91** [comment]
Thank you for information.  Even though it run very well already, improvement is always good!
Found other crash issue. Some XF problems with event's.
