### ISSUE TITLE
Difference of InfoLayer and HoverInfoLayer and behavior

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#161]
Hi Paul,

I looked into creating markers on the map and found, that I should add features by myself to a layer, add the layer to InfoLayers and attach to event Info of Map. Is this correct?

Now I have a few questions: What is the difference between HoverInfoLayers and InfoLayers? I assume, that Info event for HoverInfoLayers is called, when you move over the features in the layer while Info event for InfoLayers is only called, when you click on features. But I found on UWP, that Info is only called, when I press mouse button on feature and move with pressed mouse button. Info for HoverInfoLayers isn't even called.

I'm missing something?

Btw. is there an implementation for a call out like you have in Google Maps?

**Comment by pauldendulk** [comment]
About HoverLayers. Yes, this is only called on a mouse-over-event. It was introduced for WPF. We had something like this before we ever made a Xamarin version. It is there because of history. I am not sure if I should support it.

For Android and iOS it is less interesting, although there is now some kind of hover functionality in Android as well. I don't know about iOS. 

A problem with hover is that it could cost a lot of performance because you are querying the hover layer on every mouse move. This is a reason to remove it. There are smart implementations possible that would reduce performance costs but implementation is not in sight.

**Comment by pauldendulk** [comment]
About InfoLayer. Yes, this shows on a click event. Is there a problem with how it is implemented now for UWP?

**Comment by pauldendulk** [comment]
With a call out you mean a popup when you click a symbol. Like this:
https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple

**Comment by pauldendulk** [comment]
About InfoLayer in UWP. Is see. Apparently ManipulationCompleted is only called when there has been an actual move. This is a bug.

**Comment by pauldendulk** [comment]
@charlenni Do you have any follow up on these questions?

**Comment by charlenni** [comment]
No, thank you.
