### ISSUE TITLE
Postponed fetching issue in Layer

### ISSUE THREAD

**Issue by JakubBorek** [pauldendulk/Mapsui#166]
We've encountered an issue with the postponed fetching in Layer. When FetchingPostponedInMilliseconds is set to 0 the StartFetchTimerElapsed callback sometimes executes before the StartFetchTimer assignment at the end of ViewChanged method. This can result in NullReferenceException

My understanding is that for larger FetchingPostponedInMilliseconds values the problem would be much more rare, yet still possible.

The least intrusive fix would be to create a Timer with infinite due time and change it to the correct value in the next statement.

I can draft a pull request if you want to.

**Comment by pauldendulk** [comment]
Wow, that must have been a nasty bug to find. Thanks a lot. Yes, a pull request will be welcome.

In the current code I use a custom timer I stole from stackoverflow. Since then I changed the PCL profile, maybe there are better alternatives for this now. So if this old Timer is in your way feel free to replace it.

**Comment by pauldendulk** [comment]
@JakubBorek Any update on this?

**Comment by pauldendulk** [comment]
I could not reproduce this crash in a unit test but I added a Start and Cancel method to the Timer so that it does need to be disposed. This should fix this bug.
