### ISSUE TITLE
How to smooth animate Viewport transform ?

### ISSUE THREAD

**Issue by wangjianpeng** [pauldendulk/Mapsui#202]
Is there any way to implement smooth animate Viewport transform?

**Comment by pauldendulk** [comment]
In WPF this is used for mouse wheel scroll. Apart from that there is no support for it. For what scenario do you want to use it? 

It is probably possible to implement it yourself on top of Mapsui using a Timer and some interpolation between the current viewport and the destination viewport.

**Comment by JoeCooper** [comment]
@wangjianpeng You can do this yourself using interpolation. It takes some project-specific planning because it needs to interact laterally with other code which can control the map (such as user location tracking or the touch code) and it needs some interaction with platform specific code in order to know when to advance.

If you want, I could be hired to do this if this is a bit out of your experience. I could probably also write it in a way that @pauldendulk would accept into the main branch.

**Comment by pauldendulk** [comment]
I will close this. There will probably be some more support for this in the future but we are not working on that now.
