### ISSUE TITLE
Restore or fully remove animation in UWP

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#211]
Animation is currently not used in UWP. It should be fully restored like in WPF or fully removed.

**Comment by pauldendulk** [comment]
Also fix animation initialization in WPF

**Comment by radderz** [comment]
@pauldendulk - For animations I have suggested to do #306 

I have already implemented all the animations that you'd expect in an app, like animated pan/zoom and flick type guesters where the panning can be flung and the map slowly decelerates to stopped. The main issue is I did this using Xamarin.Forms which provides a cross platform animation API.

An example of a animated zoom would be on double tap of a location on the map, it can animate zoom about that point. similar to the UWP mouse scroll zoom but with animation. Another is where you may have some button type interation that zooms and pans to a location on the map (like a where am I feature) and rather than just centering and zooming instantly an animation feels quite natural.

**Comment by pauldendulk** [comment]
I removed the remnants of animation in uwp. A reimplementation will probably follow a whole different line as suggested by radderz.
