### ISSUE TITLE
Removing a feature from an instance of Features ? 

### ISSUE THREAD

**Issue by gklamm** [pauldendulk/Mapsui#241]
Hello Paul,

We are currently using Mapsui for a WPF desktop application, and we are trying to manage a list of features using Features (Mapsui.Providers).
To understand the Delete method and how work the PrimaryKey  property, we have checked FeaturesTests (Mapsui.Tests.Providers). But we don't understand the usefullness of all this complexity with the PrimaryKey and why there is not just a simple Remove method ?

We can make a pull request to add a simple Remove method if that's ok for you ?

**Comment by pauldendulk** [comment]
The ID is used because in some of our scenarios we fetched new features (vehicles) from a service every 15 seconden. Fetching those feature and serializing them created new instances of objects even though they referred to the same feature. That is why code like this did not work:

```csharp
public void Delete(IFeature feature)
{
    _features.Remove(feature);
}
```
I can understand this is easier for other scenarios though. Perhaps you could add something like the above. I think I prefer a Delete overload over a Remove method. Not sure if the correct overload is called if you pass an instance of Feature. I you could unit test this I would be even happier. 

Btw, I am working in the 1.1 branch now.

**Comment by pauldendulk** [comment]
@gklamm is this issue still relevant to you? If not I will pick it up myself, it is a relatively small change.

I also want to add an overload that takes a feature and a method to compare the features, so this can be used to implement value compare. This way you don't have to add the Key in the constructor, making the purpose more clear.

**Comment by pauldendulk** [comment]
Added ```Features.Delete(IFeature feature, Func<IFeature, IFeature, bool> compare = null)```, available in this beta: https://www.nuget.org/packages/Mapsui/1.3.0-beta3

**Comment by JTrotta** [comment]
It seems this methd no longer exists. How to delete a feature from Features?

**Comment by pauldendulk** [comment]
@JTrotta The entire Features class was removed. It was an extra layer that did not add much value. Instead of further developing it into a solid collection we now use the Microsoft collection classes. 

In the MemoryLayer we now have an `IEnumerable<Feature> Features` field. You can assign that with a collection you manage from you own code. It should be a thread save collection.

You could also look at the WriteableLayer that is used in the editing samples. Or copy the code of the WriteableLayer into your own code and manage it yourself.
