### ISSUE TITLE
White border on iOS on top and left side

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#245]
![image](https://user-images.githubusercontent.com/963462/32655754-46e62de6-c60f-11e7-99f5-133c8afef44f.png)

**Comment by Sebastian1989101** [comment]
Just tested a few more things. It seems like Mapsui got some weird offset (maybe a padding?) in it's control since the last update (because again, the "white" border is gone if I downgrade to 1.0.11). If the page has a different back color as the Mapsui control this "Border" appears on iOS. The line is pretty tiny and hard to see (I guess 1 pixel?).

**Comment by pauldendulk** [comment]
I still can not reproduce it. This is what I'm doing

- Run on Simulator
- iPhone X iOS 11.1
- Set MapControl background to red , Map background to blue, Skia Canvas background to yellow (see none of those colors when I zoom in).
- Tried Physical Size and Pixel Accurate (in 'Window' menu)

**Comment by pauldendulk** [comment]
Two suspects. Since 1.0.11 we use:
- SKGLView
- NSLayoutConstraint for positioning. Like this:
```
AddConstraints (new [] {
	NSLayoutConstraint.Create(this, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, _canvas, NSLayoutAttribute.Leading, 1.0f, 0.0f),
	NSLayoutConstraint.Create(this, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, _canvas, NSLayoutAttribute.Trailing, 1.0f, 0.0f),
	NSLayoutConstraint.Create(this, NSLayoutAttribute.Top, NSLayoutRelation.Equal, _canvas, NSLayoutAttribute.Top, 1.0f, 0.0f),
	NSLayoutConstraint.Create(this, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, _canvas, NSLayoutAttribute.Bottom, 1.0f, 0.0f),

	NSLayoutConstraint.Create(_attributionPanel, NSLayoutAttribute.CenterX, NSLayoutRelation.Equal, this, NSLayoutAttribute.CenterX, 1.0f, 0.0f),
	NSLayoutConstraint.Create(_attributionPanel, NSLayoutAttribute.Top, NSLayoutRelation.Equal, this, NSLayoutAttribute.Top, 1.0f, 26.0f),
	NSLayoutConstraint.Create(_attributionPanel, NSLayoutAttribute.Bottom, NSLayoutRelation.LessThanOrEqual, this, NSLayoutAttribute.Bottom, 1.0f, 0.0f)
});
```

**Comment by Sebastian1989101** [comment]
The page color should be different as white and different as the Mapsui BackColor. And if this is true I can reproduce it 100% native and forms on iOS.

**Comment by pauldendulk** [comment]
I can see a thin white line in your OpenGeoDB sample but I can not see it in Mapui.Samples.iOS. Could you send a screenshot of what you see when running Mapsui.Samples.iOS? 

If you change colors to make it more noticeable, please let me know exactly what you changed.

**Comment by Sebastian1989101** [comment]
So far as I tested, it always happens when the Mapsui control is not the full screen view. As soon as Mapsui is a nasted element in a view it gets this border (which did not happened on 1.0.11). So it should be enough to wrap the sample in a navigation page scenario.

**Comment by Sebastian1989101** [comment]
@pauldendulk did you already found the difference between 1.0.11 and the following versions? Otherwise I would spent a bit time at the weekend to modify the sample that you see how it can be done with the sample. I guess it is because with Xamarin.Forms I add a sub View into the primary view (even if I use the same Bounds for my sub view as the main view has). The only strange thing is, that it works with 1.0.11 and before.

**Comment by pauldendulk** [comment]
No, I did not look into that yet. It would be of great help if you can try to reproduce it.

**Comment by Sebastian1989101** [comment]
I do not know what I did last time but it seems to work now with the Sample in every case now. I will test a bit with Xamarin.Forms at the weekend if I can find what causes the border exactly and how it could be happen on native platforms. For release builds I'm currently still using 1.0.11 because it seems to work perfectly (except the strong limitation to other NuGet package versions).

**Comment by pauldendulk** [comment]
I suspect it is caused by the SKGLView. It could also be the attribution (less likely). I will first release a version with attribute info drawn by the renderer. If the issue still persist I will investigate it further. 

You could also test if you have the issue with an SKGLView in iOS with Forms. Without Mapsui.

**Comment by pauldendulk** [comment]
I don't particularly expect this to be solved but I made some changes that could affect this, so please check again with 1.2.0.

**Comment by Sebastian1989101** [comment]
Still present in Mapsui 1.2.1. I hope I have the time this weekend to test the SKGLView to see if this bug comes from there.

**Comment by pauldendulk** [comment]
I published a beta where the NSLayeroutContrained is removed, this could solve the issue. 
https://www.nuget.org/packages/Mapsui/1.3.0-beta2

If not we have to look into the SKGLView

**Comment by Sebastian1989101** [comment]
Just tested 1.3.0-beta2 and 1.3.0-beta3. Both has still the white border. 
![simulator screen shot - iphone x - 2017-12-30 at 23 34 53](https://user-images.githubusercontent.com/25636075/34457736-ad2cd8fc-edba-11e7-8f82-63e6c2aabe3d.png)

**Comment by charlenni** [comment]
Sebastian, if you look in the right bottom corner, there is a slider. Do you insert Mapsui in a Scrollbox? Could that be the problem?

**Comment by Sebastian1989101** [comment]
@charlenni no because it works instantly if I use 1.0.11. So it is not possible that the structure of my app page has anything todo with it. Otherwise it should be there in every version of Mapsui. The border appears from Version 1.1.1 and higher. The scroll viewer like scrollbar appears from Version 1.2.0 and newer (it isn't there on 1.1.1, 1.1.2 and 1.1.3 but the border is also in this versions visible).

**Comment by pauldendulk** [comment]
I am now investigating this. I user your OpenGeoDB sln with project references to the Mapsui projects. I now reverted Mapsui to a commit around v1.0.7 and still see the lines. The only difference with version 1.1.1 is that I cannot set the color of lines. This is because MapControl is derived from UIView. If I take that version and derive from UIStackView as in 1.1.1. I can set the MapControl background to red and then see the red lines, so also with 1.0.7.

The red line are from the MapControl which should be fully covered by the skia canvas, so this is a bug in Mapsui or Skia, or Xamarin.Forms. However, it seems the bug did not arise on version 1.1. 

Hopefully you can confirm this, otherwise I made some mistake with my testing. Which is possible because a lot of things are involved (like setting the skia references).

**Comment by Sebastian1989101** [comment]
With the OpenGeoDB it is pretty hard to see (because the map itself is pretty bright too). I did the following changes to make it "visible" there: 

1. Change the Grid to a different color in the XAML of OpenGeoDB.Core.Pages.DetailPage (set the BackgroundColor in the Grid in Line 11 to something different than white). 

2. OpenGeoDB.Core.Controls.MapsuiMap remove the Switch from Line 73-84 and set the BackColor to something different than white. 

Now you can see a thin white line at the left and top side of the map with Mapsui 1.1.1 and newer - it is gone with 1.0.11 and older. Of course you have to remove the Mapsui.Widget stuff from the MapsuiMap control within OpenGeoDB if you use older versions. You need to downgrade the iOS project Mapsui reference as well before the changes would apply. It would be much more visible if you use any dark map like this one: https://software-notion.de/botw-map/map.mbtiles

![mapsui compare](https://user-images.githubusercontent.com/25636075/34462927-1f861fc4-ee4e-11e7-9def-742a87510b09.png)

**Comment by pauldendulk** [comment]
Thanks for your elaborate feedback. Did you create the 1.0.11 version just now, by downgrading Mapsui? Did you downgrade skia as well?

**Comment by Sebastian1989101** [comment]
I just downgrade / upgrade Mapsui. But I guess the references to SkiaSharp will get downgraded / upgraded together with Mapsui through NuGet but I did not check this specificly.

**Comment by pauldendulk** [comment]
side note. If I derive the MapControl from UIStackView it is possible again to set the background color. This will be a workaround for you, no?

**Comment by pauldendulk** [comment]
If I do a clean checkout OpenGeoDB I get compile errors on DetailPage.cs

![image](https://user-images.githubusercontent.com/963462/34463387-7ef6c3da-ee5a-11e7-9179-67f50c3a5c1e.png)

**Comment by Sebastian1989101** [comment]
MapControl cannot derive from UIStackView because it is in the PCL and not in the iOS project. Otherwise I won't be able to use it in Forms properly. It also won't change the white border around it I guess because it must be something within the iOS implementation of Mapsui because it only changes if I upgrade / downgrade there. 

About the build error: Thats strange. Is there something messed up with the Build order? The core needs to build first. Just tested a clean checkout and it works asap.

**Comment by pauldendulk** [comment]
No, I mean the Mapsui MapControl. I will have to release a new version, but that would be easy to do. 

If it is derived from UIStackView (as in my current local version) you can set the color of the white line by setting the BackgroundColor of the MapControl itself.

**Comment by Sebastian1989101** [comment]
Oh that might be a workaround for that problem. At least the line would be no longer noticable by the user. Currently I'm using a negative margin to hide it behind the NavigationBar and place the left/right side outside of the screen on the projects where the line was pretty noticable like the Zelda app.

**Comment by pauldendulk** [comment]
OpenGeoDB did rebuild after deleting the obj's and bin's and some things like that. When reverting to 1.0.11 I get the screenshot below (pasted on a dark background). So, for all that I know, the line always existed. What changed in 1.1.0 is that it was not possible to set the color because MapControl is now derived from UIView instead of UIStackView. I will change this back in 1.3.0. 

The fact that there is a line is still an issue, but I don't think I will give it much priority. I assume it is a problem of Skia in combination with Xamarin forms because Mapsui does not do much other that set the SKCanvas's ClipToBound to true.

OpenGeoDB with Mapsui 1.0.11:
![image](https://user-images.githubusercontent.com/963462/34466488-72b5aad4-eed5-11e7-8d56-a7564f461d87.png)

zoomed in version:
![image](https://user-images.githubusercontent.com/963462/34466499-c312f5ae-eed5-11e7-89e3-34973bae1feb.png)

**Comment by Sebastian1989101** [comment]
Seems to be fixed with 1.3.0

**Comment by pauldendulk** [comment]
Good to hear. That was a really annoying bug :)

**Comment by Sebastian1989101** [comment]
@pauldendulk I just updated an old project to Mapsui 1.4.8 (it was on 1.3.2 before) and it looks like the issue is back. Because of an update of another component I had to update Newtonsoft.Json to 11.x which requires Mapsui to go at least to 1.4.2 and the issue is already back in this version. 

Is there any known workaround for this problem? My current workaround is a Margin with -1 on all sides (but this might cause other issues I'm not aware off yet).
