### ISSUE TITLE
Collection was modified; enumeration operation may not execute. (iOS)

### ISSUE THREAD

**Issue by Sebastian1989101** [pauldendulk/Mapsui#291]
I just started to use  cloud based analytics services for my apps and since the release yesterday I already got ~300 reports with this error (from 9500 active users since than): 

```
ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource)
List`1+Enumerator[T].MoveNextRare ()
List`1+Enumerator[T].MoveNext ()
System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) <0x10125db30 + 0x00287> in :0
Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source)
VisibleFeatureIterator.IterateLayer (Mapsui.IViewport viewport, Mapsui.Layers.ILayer layer, System.Action`3[T1,T2,T3] callback)
VisibleFeatureIterator.IterateLayers (Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers, System.Action`3[T1,T2,T3] callback)
MapRenderer.Render (SkiaSharp.SKCanvas canvas, Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers)
MapRenderer.Render (SkiaSharp.SKCanvas canvas, Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers, System.Collections.Generic.IEnumerable`1[T] widgets, Mapsui.Styles.Color background)
MapRenderer.Render (System.Object target, Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers, System.Collections.Generic.IEnumerable`1[T] widgets, Mapsui.Styles.Color background)
MapControl.OnPaintSurface (System.Object sender, SkiaSharp.Views.iOS.SKPaintGLSurfaceEventArgs skPaintSurfaceEventArgs)
SKGLView.DrawInSurface (SkiaSharp.SKSurface surface, SkiaSharp.GRBackendRenderTargetDesc renderTarget)
SKGLView.DrawInRect (GLKit.GLKView view, CoreGraphics.CGRect rect)
(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

Not sure if this happens in Mapsui or in SkiaSharp. Currently I wait that the symbol files are processed by the AppCenter to get more details (hopefully).

**Comment by radderz** [comment]
There are quite a few synchronisation locks missing through this product around using foreach iterators that can catch this out. Generally they are iterated on the main thread due to being rendering so if you add the values to the list on the main thread it may be more threadsafe.

**Comment by pauldendulk** [comment]
I assume this is Mapsui. I don't thinks there is much threading in SkiaSharp. This has high priority.

The idea is that the rendering happens on the main thread and there should be no mutations possible of those collections. Apparently there are though. 

Is there a way to tell which type of layer this is? I suspect the feature layer.

**Comment by pauldendulk** [comment]
FeatureFetchDispatcher.FetchCompleted should replace the collection of the MemoryProvider instead of modify it.

**Comment by Sebastian1989101** [comment]
I'm not sure which layer it is. Never had this exception while testing. It's within my Breath Companion app so I guess it is the Feature Layer because it has to render ~6000 Icons when everything is enabled. Would be great if the AppCenter would finally proceed with my symbol files so I maybe get a more detailed look at it..

**Comment by pauldendulk** [comment]
I released an unlisted 1.3.2-beta1 where the features MemoryProvider features are replaced instead of modified. It is a breaking change though so I am not so sure if this is a good solution.

https://www.nuget.org/packages/Mapsui/1.3.2-beta1

**Comment by Sebastian1989101** [comment]
Is the 1.3.2 beta for this still available? Can't find it on nuget anymore. I could test it tonight with multiple devices.

**Comment by pauldendulk** [comment]
Yes. That is because it is unlisted. You have to install the specific
version with the package manager console. Mapsui 1.3.2-beta1.

Paul


Op 24 jan. 2018 13:59 schreef "Sebastian Kruse" <notifications@github.com>:

Is the 1.3.2 beta for this still available? Can't find it on nuget anymore.
I could test it tonight with multiple devices.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pauldendulk/Mapsui/issues/291#issuecomment-360123962>,
or mute the thread

**Comment by Sebastian1989101** [comment]
Strange but I got the message that the creator has revoked the package if I try to update through the console command. Don't know if this is an issue with Visual Studio for Mac or I miss something. All other Beta Versions could be installed without any problems there.

**Comment by radderz** [comment]
This works fine for me on beta2, just had to make a minor change when creating the memory layer due to the breaking change of moving the feature list to the constructor property. But its a pretty minor change.

**Comment by Sebastian1989101** [comment]
Did I miss something? All of my apps still works without any changes after the update to 1.3.2. Or what exactly is this breaking change you are talking about? Well my apps go to beta testing now and will launch (if there is no problem) within the next two to three days.

**Comment by radderz** [comment]
I was setting the features of a memory provider in the initialiser rather than the constructor, which was removed as its now a private property.

**Comment by pauldendulk** [comment]
Yes, It is a minor breaking change. There are many possible breaking changes that will hardly be noticed by anyone.

**Comment by Sebastian1989101** [comment]
Seems to be fixed since 1.3.2-beta2. At least I got no reports anymore about this crash.

**Comment by pauldendulk** [comment]
great

**Comment by tkopton** [comment]
I am using 1.4.7 and the: "Collection was modified; enumeration operation may not execute."

Is thrown after few seconds of using my app.

This is the stack trace:

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:1186
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:1180
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].ToList () [0x0002d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/external/corefx/src/System.Linq/src/System/Linq/Select.cs:161
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30
  at Mapsui.Rendering.Skia.MapRenderer.Render (System.Object target, Mapsui.IViewport viewport, System.Collections.Generic.IEnumerable`1[T] layers, System.Collections.Generic.IEnumerable`1[T] widgets, Mapsui.Styles.Color background) [0x00025] in <80b75f592c3148dcb5b35a389ab77fe0>:0
  at Mapsui.UI.iOS.MapControl.OnPaintSurface (System.Object sender, SkiaSharp.Views.iOS.SKPaintSurfaceEventArgs args) [0x00072] in <c5bd075791cf45e999643c33be9edffc>:0
  at SkiaSharp.Views.iOS.SKCanvasView.DrawInSurface (SkiaSharp.SKSurface surface, SkiaSharp.SKImageInfo info) [0x00013] in <f98a23a33dc2487084ebd8ef6d9407d2>:0
  at SkiaSharp.Views.iOS.SKCanvasView.Draw (CoreGraphics.CGRect rect) [0x00048] in <f98a23a33dc2487084ebd8ef6d9407d2>:0
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at app_test_01.iOS.Application.Main (System.String[] args) [0x00001] in /tmp/Projekt-Code/app_test_01/app_test_01.iOS/Main.cs:17


I suppose, this is because I do this 24 times in the second:

var planeLayer = mapControl.NativeMap.Layers[3];
mapControl.NativeMap.Layers.Remove(planeLayer);
planeLayer = null;
planeLayer = GeneratePlane();
mapControl.NativeMap.Layers.Add(planeLayer);

I do not like it but I did not figure out how to move a point on the map (moving plane).

**Comment by tkopton** [comment]
I tried several things like try/catch and lock, but still no luck. I suppose this part of the code, which is called every second is causing the issue:


`mapControl.NativeMap.Layers.Remove(mapControl.NativeMap.Layers[4]);
mapControl.NativeMap.Layers.Remove(mapControl.NativeMap.Layers[3]);
mapControl.NativeMap.Layers.Remove(mapControl.NativeMap.Layers[2]);
mapControl.NativeMap.Layers.Insert(2, GenerateWPLayer());
mapControl.NativeMap.Layers.Insert(3, CreateLineStringLayer());
mapControl.NativeMap.Layers.Insert(4, GeneratePlane());`

Any idea how to achieve the modification of the layer without hitting the issue?

**Comment by charlenni** [comment]
It's hard to suggest anything, if you don't say, what your layers do and what you change every second.

**Comment by tkopton** [comment]
All three layers has:

`DataSource = new MemoryProvider()`

The first one is drawing points (in my case way points)

`var point = new Point(WayPoints[j].Lat, WayPoints[j].Lon);
 var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(point.Y, point.X);
var feature = new Feature
{
   Geometry = sphericalMercatorCoordinate
};
features.Add(feature);`

The second layer is connecting the points:

`var point = new Point(WayPoints[j].Lat, WayPoints[j].Lon);
var sphericalMercatorCoordinate = SphericalMercator.FromLonLat(point.Y, point.X);
lineString.Vertices.Add(sphericalMercatorCoordinate);`

And the third one is using a png file as SymbolStyle to draw a symbol on the map.

What I would like to achieve to redraw all three layers because the position of the symbol on the map changes, the way points including the connecting lines should be removed as soon as a point has been reached.
Because I do not know any other way of adjusting the features included in a layer, I am removing the layers and creating them from scratch. I suppose this is where some kind of race condition occurs.

**Comment by charlenni** [comment]
For this, you don't have to delete the Layer. It's time consuming and you get in trouble, as you see ;).

A better way to do this, is to change the Features property of your MemoryProvider. Use for this

````
public void ReplaceFeatures(IEnumerable<IFeature> features)
````

of MemoryProvider. So save your way points into a List<Feature> and adjust this list. If something changes, replace the list of features of the MemoryProvider with your list. Perhaps you have to refresh the MapControl. That's all. The same for the lines.

The single symbol is much easier. You only save the Feature you use for the symbol and when the position of the symbol should change, update the Geometry of the Feature. Refresh map. That's it.

**Comment by tkopton** [comment]
This is what I actually wanted to do but failed at the "DataSource" attribute.

`private ILayer GenerateWPLayer()
        {
            var layername = "ElaWaypoints";
            return new Layer(layername)
            {
                Name = layername,
                DataSource = new MemoryProvider(GetElaWayPoints()),
                Style = new SymbolStyle
                {
                    SymbolScale = 0.5,
                    Fill = new Brush(Color.Black),
                    Outline = { Color = Color.Black, Width = 1 }
                }
            };
        }`

If I now use e.g. mapControl.NativeMap.Layers[4]. I can access the Name and Style attribute but there is no DataSource presented by the Visual Studio. I suppose, I need to use GetFeaturesInView somehow. Do you have any code examples for me? That would be very helpful. I have another very stupid question, how do you refresh the map the easiest way?

**Comment by charlenni** [comment]
mapControl.NativeMap.Layers is of type ICollection<ILayer>. So you have to use 
````
(Layer)(mapControl.NativeMap.Layers[4]).DataSource.MemoryProvider
````
That should do the trick.

A sample is [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/MutatingTriangleSample.cs). It is slightly different from what I suggest. 

Another sample (see [here](https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/AnimatedPointsSample.cs) shows the use of an own MemoryProvider. MemoryProvider derives from IProvider. The only thing, you have to do, is to implement the functions
````
IEnumerable<IFeature> GetFeaturesInView(BoundingBox box, double resolution);
````
and
````
BoundingBox GetExtents();
````
That's very easy. The first returns a list of alle features in the BoundingBox, the seconds returns the area, which your features cover. With this, you could return each time the map changes, all features you want to show. The only you have to do, is to update the MapControl every minute. Mapsui than asks your provider for all feature, which should be displayed on map.

**Comment by charlenni** [comment]
Ah, easiest way to refresh map (see [here](https://github.com/Mapsui/Mapsui/blob/master/Mapsui/UI/IMapControl.cs) )
````
mapControl.Refresh();
````

**Comment by tkopton** [comment]
Thank you very much for your help. The first example looks very promising, this is exactly what I was looking for. I will give it a try over next weekend. 

The Refresh() is still not clear.
My mapControl class is:

`
public class MapsUIView : Xamarin.Forms.View
    {
        public Mapsui.Map NativeMap { get; }

        protected internal MapsUIView()
        {
            NativeMap = MbTilesSample.CreateMap();
            NativeMap.BackColor = Mapsui.Styles.Color.Gray; //This Color should match the map
        }
    }
`

I suppose I need to cast here:

`mapControl = (Mapsui.UI.IMapControl)new MapsUIView();`

I need to test this, too.

Many thanks again.

**Comment by tkopton** [comment]
This is more complicated than I thought, at least for me. The part with updating the Geometry seems to be relatively straight forward but the refreshing is an issue.

1. To use the map as a xamarin view, my class inherits from Xamarin.Forms.View, that means, I cannot inherit from MapControl ergo, no Refresh() method. I could implement the Interface but after I checked the implementation in MapsUI, it does not looks that easy for a beginner.

2. layer.RefreshData(layer.Envelope, 1, true); does not work, there is no RefreshData() in MemoryLayer, in my MapsUI 1.4.7.

**Comment by tkopton** [comment]
Got it:

layer.ViewChanged(true, layer.Envelope, 1);

**Comment by charlenni** [comment]
You could do it with messages. Look into the code of my old Mapsui.Forms implementation [here](https://github.com/charlenni/Mapsui.Forms). I create a message in the MapView and that message is received by the renderer, which calls the refresh of the MapControl.

**Comment by tkopton** [comment]
It looks like I managed to implement charlenni's ideas.

`layer.DataSource = new MemoryProvider(MyFeatureProvider());
layer.ClearCache();
layer.ViewChanged(true, layer.Envelope, 1);`

works for me.

Many thanks again.
