### ISSUE TITLE
How to draw a info box for marker

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#308]
Is it possible to draw a info box/call out for a marker? If yes, how to do this? If no, how to implement this?

**Comment by pauldendulk** [comment]
The Info method returns coordinates that can be used to show a 'native' control on top of the Map. The InfoSample run on Android shows how this could work.

**Comment by pauldendulk** [comment]
Here is how the popup is positioned:
https://github.com/pauldendulk/Mapsui/blob/master/Samples/Mapsui.Samples.Android/Activity1.cs#L92

For Xamarin.Forms a user could implement something similar for his/her purpose.

With the widgets that are now introduced we could start to think of way to implement this in Mapsui itself to make it easier for users.

**Comment by charlenni** [comment]
Widgets are not correct for this, because they stay on the map and don’t move with it.

Callouts should be drawn in MapControl, because it is useful, if you could not only use text, but a platform dependent view too. For this, MapControl should have a function, which gets a View/UIView, calculats the size of this view, draws a bubble around this view and adds it to the subviews, moves the map to a position, so that the bubble is visible, and displays it. If the user clicks into the bubble, an event should be fired. If the user clicks outside, the bubble should vanish.

Easy, isn’t it 😉

**Comment by radderz** [comment]
@charlenni - popups like this may not be ideal in mapsui due to the size constraints of the screen, in other platforms the popups will change for as they get near the edge of the screen,

This is how I have done it using an "Overlay" rather than a popup. If you look at google maps as an example they have begun using overlays more than popups. This is much easier to code and I change the content on click of a feature. The only thing I need to figure out is how to highlight that feature but maybe I'll make it larger or something to show it is the one that is selected.

![image](https://user-images.githubusercontent.com/1195471/35937308-b7d25e26-0caa-11e8-8d0a-d1d5268eba71.png)

In Xamarin.Forms I have built that overlay using a transparent frame (thats an image from UWP so you can't see the shadow). And the overlay widget for selecting layers (which contains things like satellite view, traffic options etc and centering on user location. @pauldendulk the middle button that looks like a compass rotates with the map and allows for resetting to north. This is the type of widget I was poorly trying to explain re the snapping/unsnapping rotation.

**Comment by radderz** [comment]
It isn't open source as its a comercial application from my company, however its pretty simple to acheive,

I made the page have a grid, with two rows, I added the map to be spanning both rows then I added the bottom "frame" which is a content control to the second row and the widget to the first row. Using the opacity features in Xamarin.Forms to give it the background transparency (you could also just use a semi tranpsarent colour as the background.

This doesn't really need to be part of Mapsui as you can easily add an overlay overtop of the view in the environment you are working with and use the info event to trigger the change.

In my case I don't hide it once you have selected an asset and the content just changes when a different asset is selected. Otherwise you could just put an "X" at the top or handle when a click occurs that is on the map that isn't within the overlay.

**Comment by pauldendulk** [comment]
@charlenni I am trying to prevent more code/functionality in the platform specific MapControls. 

Initially i implemented the attribution as platform specific controls (with the idea that I could reuse the platforms click logic) but that proved hard to implement, because you need knowledge of each platform, hard to maintain and it caused many curious bugs. Also you have 4 implementations that you need to keep in line. The current widget solution is much better, although it still needs two implementations. Also our plans to merge more MapControl code into one partial class are a good way to go forward.

With the current implementation it is already possible to show a widget for the user. Also in your Xamarin.Forms solution you could add such a popup defined in Xamarin.Forms classes.

**Comment by charlenni** [comment]
Yes, you are both right.

I’m in the process of evaluation, which things belong to Mapsui, which belong to Xamarin.Forms and which belong to an App. If it is useful for WPF, it belongs to Mapsui. If it is useful on all mobile platforms and for more than an App, it belongs to Xamarin.Forms implementation.

**Comment by pauldendulk** [comment]
I think there is a use for an InfoWidget similar to what radderz posted above, but it will be simpler. It will be useful for a quick start, and for my samples. In my InfoSample I now use a native control for each platforms. For a a nice UI you need to create one in your own app code though.

**Comment by pauldendulk** [comment]
About WPF. This will also have a Xamarin.Forms implementation at some point so it will not differ much from the other platforms.

**Comment by pauldendulk** [comment]
Closing this now. Please start new issues for specific questions/requests that come out of this discussion.

**Comment by sandeepams** [comment]
Hi @radderz , i've been trying to show markers on map, can you please help me, how you achieve loading markers on map. I'm using mapsui xamarin forms.

**Comment by pauldendulk** [comment]
@sandeepams There is a 'Simple Points' sample to show markers on the map. Perhaps you problem is with converting lat/lon to SphericalMercator. In that case look at SphericalMercator.FromLonLat(...).
