### ISSUE TITLE
.net standard support?

### ISSUE THREAD

**Issue by swapnil591** [pauldendulk/Mapsui#343]

**Comment by pauldendulk** [comment]
It is planned for 2.0.https://github.com/pauldendulk/Mapsui/wiki/Mapsui-2.0.

What is your scenario? It is possible to use PCLs in most cases?

**Comment by michalhoblik** [comment]
Hi Paul,

the situation is currently so: the new Visual Studio 2017 (15.5.6 I think is the Version number) has no more PCL Templates (Xamarin.Forms) inside and you can just choose between "Shared" and ".NET Standard" Project type for all new Xamarin Projects. So I think Mapsui and .NET Standard should be in near future consider. I found a way how to port a PCL Nuget inside a .NET Standard Project and tried it with Mapsui and is working fine. Just the compiler is complaining, that a PCL Component has been added to the .NET Standard Solution and that some unexpected behavior can occurs.

**Comment by pauldendulk** [comment]
I was thinking about a 2.0 with some minor breaking changes. Perhaps we should just push for netstandard as well.

**Comment by michalhoblik** [comment]
I would recommend to push that for a 2.0 version. I cant currently say how long my "hack" with PCL Library inside a .NET Standard Project will be working (I did not knew till this monday that PCL Templates did not exist anymore till I had to create a new project). And with currently no option in the newest VS2017 to make an old PCL Template for Xamarin Projects, I think it will be really good for this Project to make an .NET Standard Part in order to prevent problems on the side of current developers and the future ones.
