### ISSUE TITLE
In WPF MapControlMouseLeftButtonUp.MouseButtonEventArgs.ClickCount is always 1

### ISSUE THREAD

**Issue by pauldendulk** [pauldendulk/Mapsui#344]
It seems to be by design: https://social.msdn.microsoft.com/Forums/en-US/06520016-33ef-4c55-9da6-9576a83ad237/clickcount-stuck-at-1-with-mouseup-event?forum=wpf

For MapControlMouseLeftButtonDown.ClickCount can be 2.

I will commit a 'fix' where our current MapControlMouseLeftButtonUp event will be attached to the MapControls MapControlMouseLeftButtonDown event. It seems to solve my problem. The question is. What will this break?

It is now weird that there are two events coupled to the same event but that can be fixed by merging the two methods. I am not sure though what else could go wrong.

**Comment by pauldendulk** [comment]
@radderz What do you think?

**Comment by pauldendulk** [comment]
oh, my solution completely breaks panning. Also you don't want feature info on mouse down because that could be the beginning of a pan movement.

**Comment by pauldendulk** [comment]
Maybe for my problem I should just listen to the controls mouse down and get the feature info from that event.

**Comment by radderz** [comment]
@pauldendulk , I actually never did the WPF implementation as I couldn't see an obvious click count property as I don't do much WPF work. I had planned to go back and make an implementation of a click recognizer but I never got around to it. 

I was thinking to basically implement it the way the current click worked, but with a short timer (trial and error on this) before it fires to the info event and if a second click event occurs to then kill the timer and send the click event with 2 as the num clicks. And if it doesn't occur to raise teh event with 1 click. I guess it also would need to track the location of that click.

If you want to implement this, go ahead, otherwise I'll do it when I get a chance.

**Comment by charlenni** [comment]
I did it this way for the Forms control. I used a timer to wait, if there is another click. Works good.

**Comment by pauldendulk** [comment]
Would it not be possible to use the platform specific functionality for this? 

Another option is to not create our own events at all but add an extension method on the EventArgs to fetch the information that is now part of the InfoEventArgs. It will need some argument though. 

The risk of creating our own event handling is that we have to start implementing everything that the native events offer in our own versions.

**Comment by pauldendulk** [comment]
I am going to close this because I solved my own issue. The suggestions for other gesture recognizers should perhaps be discussed elsewhere.

For my purposes I now use the events of the platform itself (not the Info event) and request the info that I need from within that event. This seems a simpler approach with all freedom to the application developer. Mapsui is not in between them and the platform. I just added GetMapInfo method that returns the InfoEventArgs. I am going to further separate this from event handling. It should just be simple method.
