### ISSUE TITLE
Problems with betas at AppVeyor

### ISSUE THREAD

**Issue by charlenni** [pauldendulk/Mapsui#359]
I updated to 1.3.3-beta1.252 and get an "PresentationSource = null" error when change RenderMode to Skia. When going back to 1.3.3-beta1.226, the error vanishes, but comes again with 1.3.3-beta1.227. So there is a problem.

**Comment by pauldendulk** [comment]
I work with a latest build package in some of my project and do not have this problem. I know of another user who does have problem with this. 

Perhaps it is because the SVG version of SkiaSharp is different than the regular version. Depending on the build perhaps the older dll is copied to output. Or something related.

**Comment by pauldendulk** [comment]
I looked into the history of AppVeyor and build 227 (the number at the end is the AppVeyor build number) is triggered from this commit: 
"Merge pull request #348 from charlenni/SharedProject"'
https://github.com/pauldendulk/Mapsui/commit/815e27385ec95337628cd2a849e9ffb65404b550

Thanks for checking the exact build version where it fails, good detective work.

**Comment by charlenni** [comment]
It is a problem with this part of code:

        private float GetSkiaScale()
        {
            var presentationSource = PresentationSource.FromVisual(this);
            if (presentationSource == null) throw new Exception("PresentationSource is null");

When changing to Skia renderer in the constructor, than this function crashes.

**Comment by pauldendulk** [comment]
Yes, but that is probably because it is the first time it is trying to load the skia dll.

**Comment by pauldendulk** [comment]
I see, nothing to do with skia yet.

**Comment by pauldendulk** [comment]
Why do you think it can not be called there? The window has been initialized long before.

**Comment by pauldendulk** [comment]
Perhaps it does need to initialize when setting the Visibility to Visible.
```
                    RenderCanvas.Visibility = Visibility.Collapsed;
                    RenderElement.Visibility = Visibility.Visible; // Start initialze
                    Renderer = new Rendering.Skia.MapRenderer();
                    _scale = GetSkiaScale(); // not fully initialized yet.
```

**Comment by pauldendulk** [comment]
What if you start with skia rendering right away?

**Comment by pauldendulk** [comment]
It is hard to judge if this code it correct. The _scale is always one. The scale is requested from the main window. I wonder if that is correct in the first place. Perhaps the RenderElement should be passed to the GetSkiaScale method. But then again this, is also always 1. Why not disable this code until we run into a situation where we actually need it.

**Comment by charlenni** [comment]
Ok, you could be right and it is in all cases 1. But are you sure? The suggestion from above (move it to MapControlSizeChanged() ) works and isn't called to often.

**Comment by charlenni** [comment]
Perhaps I set it at the wrong place. I set the RenderMode in constructor of the main window. To early?

**Comment by pauldendulk** [comment]
Ah, you set it to skia from the outside on startup. Then it probably is the initialization issue discussed here:
https://stackoverflow.com/questions/11204251/presentationsource-fromvisualthis-returns-null-value-in-wpf

The problem of setting it in MapControlSizeChanged is that you don't actually know if skia is active at that point. You might be requesting it for wpf. I could think of a workaround where we get it in the renderloop and check if it needs updating with some boolean, but since I can not check if it is correct (because it always return 1), I think I will just remove it.

**Comment by pauldendulk** [comment]
Fixed this with this commit:
https://github.com/pauldendulk/Mapsui/commit/98a11ed22e7c80ea0b5a4b9946147f119fd84c55
