### ISSUE TITLE
Ideas for improving release cycle time

### ISSUE THREAD

**Issue by kwesolowski** [pauldendulk/Mapsui#49]
It would make versioning and releasing faster if common assembly version data will be stored in single file (and the same version can be then used in nuget).

Is something blocking such approach (like http://www.purecs.net/csharp/tips-and-trick-1/share-a-globalassemblyinfo-file-among-projects-in-a-solution)? I can draft some Pull Request.

**Comment by pauldendulk** [comment]
There is nothing blocking this. I use something like this in BruTile. 
https://github.com/BruTile/BruTile/blob/master/SharedAssemblyVersion.cs
But Mapsui's release is just as easy because a script is updating the assembly version for all files. See the scripts\readyme.txt here: https://github.com/pauldendulk/Mapsui/tree/master/Scripts (it still mentions hg where it should be git).

I think a shared assembly version is nicer but it won't make the release much faster. 

The main reasons releases are slowed is because I don't have scheduled time for Mapsui maintenance and I get easily swamped in other work. I expect this to improve in the coming period.

For the next release: 
- This issues still needs to be fixed https://github.com/BruTile/BruTile/issues/23
- Also I am in the process of moving Geometries to a separate project and need to update the mapsui.nuspec and build.proj

Another improvement would be to release nigtly builds.

**Comment by kwesolowski** [comment]
I also consider all version "quite beta" and this is why I would love shorter release cycle - event as 0.6.4-beta :) But if any work can make your life easier I would like to help - we are using Mapsui now in WPF app.

**Comment by pauldendulk** [comment]
The beta postfix can be used to distinguish between beta en actual releases but since I don't have any actual releases this won't work. Therefore I should just release a version that is relatively stable.

**Comment by kwesolowski** [comment]
I was thinking about nuget version `0.6.4-alpha` - such packages can be used with "Allow PreRelease" checked, and are considered older than `0.6.4`.

**Comment by pauldendulk** [comment]
We could use alpha beta postfixes after 1.0. This will make the release cycle quicker. 

Another improvement would be to add nightly builds are also nice. This will need some changes on the buildserver. Perhaps AppVeyor has some functionality for this.
