### ISSUE TITLE
Possible memory leak Tile Layer MemoryStream

### ISSUE THREAD

**Issue by 88madri** [pauldendulk/Mapsui#77]
Hi I'm using Mapsui with WPF. I notice that when using a OSM layer or a Bing layer (Tile Layers). 
When I zoom or pan to new areas (mapsui tries to download new tiles). the memory increases but when I finalize the operation the memory does not get free. I try with wpf.samples project and I have the same results. By taking some memory heaps I think the problem can be in using memorystreams because is the class that increase memory between memory snapshots. Any hints about this??

**Comment by pauldendulk** [comment]
Hi Madri, I have looked into memory usage before. I do not have the exact measurements that I would like but I have not seen any memory leaks so far. A few things relevant:

* I am not calling Dispose on MemoryStream but since Jon Skeet says that just alright I am totally cool about that: http://stackoverflow.com/a/234257/85325
* Memory fragmentation could play a part. Especially when you use big and smaller memory chunks together memory usage could increase even when the total objects in memory do not.
* There are a number of tiles in the tiles cache. This number has a certain upper threshold. So the number of tiles keeps rising until that threshold is reached. When reached the number of tiles decrease to a lower threshold. This could cause variation in memory usage. 

I would love to have some very exact test in my code where I can measure the amount of memory used before and after an operation.
