### ISSUE TITLE
Multitouch-rotation function in iOS/Android

### ISSUE THREAD

**Issue by kochizufan** [pauldendulk/Mapsui#8]
Hello, I want to ask specification of Mapsui in iOS/Android.

Does mapsui have, or can be hack, to handle map to rotate by multi-touch?
In iOS and Android.

I can't find such property in MapControl class...

**Comment by kochizufan** [comment]
Hi, are there any plans to implement this function?

**Comment by pauldendulk** [comment]
Not in the upcoming release. I'm working on Skia rendering which will at some point also be used for Android and iOS. In Mapsui.Samples.Wpf you can see it in action (select the skia renderer from the dropdown top left). You can rotate the map with the slider (bottom right). As you can see rotation does not work for Tiles, WMS images and the rotation of symbols. Rotation can be complicated. Especially because the current code was not written with this in mind. I am not sure if I should go for a Canvas wide transform matrix or implement it for each geometry type.

**Comment by pauldendulk** [comment]
Update: Skia sharp is now implemented for iOS and Android. Still specific plans to implement map rotation.

**Comment by pauldendulk** [comment]
With [this pull request](https://github.com/pauldendulk/Mapsui/pull/214) it is now possible to rotate the skia renderer by setting the Viewport.Rotation property. The iOS MapControl also supports rotation by touch. The other MapControls don't support touch by rotation yet.

**Comment by JoeCooper** [comment]
I've put in a pull request today which adds touch rotation to the Android MapControl.

**Comment by pauldendulk** [comment]
Joe's PR has been released today as part of Mapsui 1.1.1. It contains rotation for iOS and Android, not UWP yet. By default is it turned off. It can be turned on with ```MapControl.AllowPinchRotation = true```.
