### ISSUE TITLE
Root ViewController missing

### ISSUE THREAD

**Issue by YordanYanakiev** [pauldendulk/Mapsui#89]
Hello.
By some reason I am unable to run the iOS demo.
The error is "NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch "

Please update the demo according to the latest iOS build requirements.
( iOS 9+, XCode 7.2+ )

**Comment by pauldendulk** [comment]
Thanks for the notice. This sample must have broken due to framework updates because I did not change anything for a long time. I have been without a macbook at home for a long time but just bought a new one so can take a look soon. The other iOS sample, that uses the UIKit, should work tough. I committed it recently.

**Comment by YordanYanakiev** [comment]
Oww.. I actually miss the UIKit one. Thanks for the note, I am on it to try it out ! :)

**Comment by pauldendulk** [comment]
Fixed in the new iOS sample.
