### ISSUE TITLE
Problem in Rasterizing a MemoryProvider data source

### ISSUE THREAD

**Issue by MehdiRahmati** [pauldendulk/Mapsui#92]
Hello pauldendulk
when i use bellow  code to Rasterize my earthquakes points (up to 50000 point), at first everything is OK and map responses to mouse normally but after some zooming and moving on map (about 6 minute), i face to a map that responses very very slowly. in your samples you used small  shapefile data source that works fine, but it seems that the issue maybe in MemoryProvider or RasterizingLayer. 
thank you 

my code:

MapControl.Map.Layers.Clear();
MapControl.Map.Layers.Add(OsmSample.CreateLayer());
MemoryProvider m_p = new MemoryProvider();
 Feature feature;
 Random rnd = new Random();
 for (int i = 0; i < 10000;i++)
  {
      feature= new Feature { Geometry = new Mapsui.Geometries.Point(rnd.Next(100000,5000000),  rnd.Next(100000,5000000)) };
     m_p.Features.Add(feature);
 }
Layers.MemoryLayer ly = new Layers.MemoryLayer();
ly.DataSource = m_p;
Mapsui.Layers.RasterizingLayer rs = new Layers.RasterizingLayer(ly);
MapControl.Map.Layers.Add(rs);

**Comment by pauldendulk** [comment]
Your code looks correct.

What platform do you use? (WPF/Android/iOS)?

**Comment by MehdiRahmati** [comment]
I use wpf in vs2015.

**Comment by MehdiRahmati** [comment]
i am waiting for your reply paul. thank you.

**Comment by MehdiRahmati** [comment]
On 2016-09-07 23:50, Paul den Dulk wrote:

> Reopened #92 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

I use wpf in vs2015.

  

Links:
------
[1] https://github.com/pauldendulk/Mapsui/issues/92
[2] https://github.com/pauldendulk/Mapsui/issues/92#event-781408229
[3]

**Comment by pauldendulk** [comment]
Does the application recover if you wait a minute en then continue?

**Comment by MehdiRahmati** [comment]
No,usage of RAM increase and map reactions slow down and dos't recover.  I found that in "DisposeRenderedGeometries" function in "RasterizingLayer" class
 , the line " disposable.Dispose();" never execute and maybe this cause program to be slow.

**Comment by pauldendulk** [comment]
With less features the problem is less severe? If so this would indicate a problem with rendering of the features and  not the rasterization itself.

**Comment by MehdiRahmati** [comment]
I think that number of features is no matter, because in first, every thing is ok and after some times i face to this problem. instead in RasterizingLayer class we have a MemoryPprovider as a cash. in Rasterize function by default every 500ms or when layers data changes we make a raster feature from rastrizer result(bitmap stream) and save it in cash. to avoid memory problems we use  RemoveExistingFeatures function before renew cash content but unfortunately this function never dispose old raster features and i think this cause the problem.

**Comment by pauldendulk** [comment]
This one took me a while. The memory profiler showed that there were much more WPF objects than should be expected. I scrutinized all my code to see where I could have leaked them. This is usually some kind of cache that keeps growing. When I could not find anything I started some wild guess googling and found this. WPF objects are not automatically collected when on a STA thread:

https://connect.microsoft.com/VisualStudio/feedback/details/568622/creating-wpf-usercontrol-in-sta-thread-causes-memory-leak

About dispose. Not calling Dispose can sometimes cause memory problems but this is usually in a tight loop. Correctly implemented Disposable objects will eventually be disposed by the garbage collector. This was not the case here since the memory kept growing. Also Dispose needs not be called on a MemoryStream. http://stackoverflow.com/questions/4274590/memorystream-close-or-memorystream-dispose

Thanks for your specific sample. This helps a lot. I willl add it to the samples in Mapsui.Samples.Wpf
